language: cpp
os: linux
dist: trusty
compiler:
  - g++
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov
 
before_install:
#  - export CC=gcc-5
#  - export CXX=g++-5
 - sudo apt-get -qq update
 - sudo apt-get install -y libgtest-dev
#  - sudo wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
#  - sudo tar xf release-1.8.0.tar.gz
#  - cd googletest-release-1.8.0
#  - sudo cmake -DBUILD_SHARED_LIBS=ON .
#  - gcc --version
#  - gcc-5 --version
#  - g++-5 --version
#  - cmake --version
#  - sudo make
#  - sudo cp -af googletest/include /usr/include
#  - sudo cp -af googlemock/gtest/libgtest_main.so googlemock/gtest/libgtest.so /usr/lib/
# #  - which valgrind
 - cd "${TRAVIS_BUILD_DIR}"
before_script:
 - cd test/cpp
 - pushd gtest && ./build.sh && popd
 - mkdir -p build && cd build
 - cmake ../
 - make
script: "./LeetCode-CXX"
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - x-jj@foxmail.com
  email:
    on_success: never
    on_failure: change
rvm:
  - 9.00
