language: cpp
os: linux
dist: trusty
compiler:
  - gcc
# addons:
#        apt:
#          packages: &precise_latest_boost_packages
#            - gcc-4.8
#            - g++-4.8
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libgtest-dev
 - sudo wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
 - sudo tar xf release-1.8.0.tar.gz
 - cd googletest-release-1.8.0
 - sudo cmake -DBUILD_SHARED_LIBS=ON .
 - sudo make
 - sudo cp -af googletest/include /usr/include
 - sudo cp -af googlemock/gtest/libgtest_main.so googlemock/gtest/libgtest.so /usr/lib/
#  - which valgrind
 - cd "${TRAVIS_BUILD_DIR}/test/cpp"
before_script:
 - mkdir -p build && cd build
 - cmake ../
 - make
script: "./LeetCode-CXX"
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - x-jj@foxmail.com
  email:
    on_success: never
    on_failure: change
# rvm:
#   - 9.00
